#spring:
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      javax:
#        persistance:
#          validation:
#            mode: none
#
#
#  datasource:
#    generate-unique-name: false